dist: xenial

language: cpp
compiler:
  - clang

git:
  depth: 1

addons:
  apt:
    packages:
      - libboost1.58-dev
      - libboost-filesystem1.58-dev
      - libboost-iostreams1.58-dev
      - libboost-program-options1.58-dev
      - libboost-regex1.58-dev
      - libboost-system1.58-dev
      - libboost-thread1.58-dev
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev
      - p7zip-full

services:
  - mysql

script:
  - rm -rf .git
  - chmod +x release-tdb.sh
  - ./release-tdb.sh
